[tool.black]
line-length = 120
include = '\\.(py)$'

[tool.isort]
profile = "black"
line_length = 120
known_first_party = ["gui", "business_logic"]

[tool.pytest.ini_options]
addopts = "-q"

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"
